/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import ui.custom.RoundedCornerBorder;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */
public class tela_cadastro_pet extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro_pet
     */
    public tela_cadastro_pet() {
        initComponents();
        initMenuPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_CadastrarPet = new javax.swing.JLabel();
        label_nome_do_pet = new javax.swing.JLabel();
        txtf_nome_Pet = new javax.swing.JTextField();
        javax.swing.JLabel label_raca = new javax.swing.JLabel();
        txtf_Raca = new javax.swing.JTextField();
        lbl_Castrado = new javax.swing.JLabel();
        chkBx_Sim = new javax.swing.JCheckBox();
        chkBx_Nao = new javax.swing.JCheckBox();
        lbl_Vacinas = new javax.swing.JLabel();
        jbtn_AddVacinas = new javax.swing.JButton();
        label_porte = new javax.swing.JLabel();
        txtf_telefone = new javax.swing.JTextField();
        label_cor = new javax.swing.JLabel();
        txtf_Cor = new javax.swing.JTextField();
        label_sexo = new javax.swing.JLabel();
        jcmbBx_Sexo = new javax.swing.JComboBox<>();
        label_comportamento_do_pet = new javax.swing.JLabel();
        jtxtArea_Comportamento = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_Saude = new javax.swing.JLabel();
        jtxtArea_Saude = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jbtn_cadastrarPet = new javax.swing.JButton();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetAgenda - Cadastrar Pets");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(899, 617));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_CadastrarPet.setFont(new java.awt.Font("Merriweather", 0, 45)); // NOI18N
        lbl_CadastrarPet.setForeground(new java.awt.Color(0, 0, 0));
        lbl_CadastrarPet.setText("Cadastrar pets");
        jPanel1.add(lbl_CadastrarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 20, -1, -1));

        label_nome_do_pet.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_nome_do_pet.setForeground(new java.awt.Color(0, 0, 0));
        label_nome_do_pet.setText("Nome do Pet:");
        jPanel1.add(label_nome_do_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 84, -1, -1));

        txtf_nome_Pet.setBackground(new java.awt.Color(217, 217, 217));
        txtf_nome_Pet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtf_nome_Pet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtf_nome_Pet.setCaretColor(new java.awt.Color(0, 0, 0));
        txtf_nome_Pet.setMinimumSize(new java.awt.Dimension(250, 50));
        txtf_nome_Pet.setPreferredSize(new java.awt.Dimension(250, 50));
        txtf_nome_Pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_nome_PetActionPerformed(evt);
            }
        });
        jPanel1.add(txtf_nome_Pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 103, -1, -1));

        label_raca.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_raca.setForeground(new java.awt.Color(0, 0, 0));
        label_raca.setText("Raça:");
        jPanel1.add(label_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 84, -1, -1));

        txtf_Raca.setBackground(new java.awt.Color(217, 217, 217));
        txtf_Raca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtf_Raca.setForeground(new java.awt.Color(0, 0, 0));
        txtf_Raca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtf_Raca.setCaretColor(new java.awt.Color(0, 0, 0));
        txtf_Raca.setMinimumSize(new java.awt.Dimension(200, 50));
        txtf_Raca.setPreferredSize(new java.awt.Dimension(250, 50));
        txtf_Raca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_RacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtf_Raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 103, -1, -1));

        lbl_Castrado.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        lbl_Castrado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Castrado.setText("Castrado:");
        jPanel1.add(lbl_Castrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        chkBx_Sim.setBackground(new java.awt.Color(255, 255, 255));
        chkBx_Sim.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        chkBx_Sim.setForeground(new java.awt.Color(0, 0, 0));
        chkBx_Sim.setText("SIM");
        chkBx_Sim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chkBx_Sim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkBx_Sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_SimActionPerformed(evt);
            }
        });
        jPanel1.add(chkBx_Sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        chkBx_Nao.setBackground(new java.awt.Color(255, 255, 255));
        chkBx_Nao.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        chkBx_Nao.setForeground(new java.awt.Color(0, 0, 0));
        chkBx_Nao.setText("NÃO");
        chkBx_Nao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chkBx_Nao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(chkBx_Nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        lbl_Vacinas.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        lbl_Vacinas.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Vacinas.setText("Vacinas:");
        jPanel1.add(lbl_Vacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jbtn_AddVacinas.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_AddVacinas.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jbtn_AddVacinas.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_AddVacinas.setText("ADICIONAR");
        jbtn_AddVacinas.setBorder(new RoundedCornerBorder(16));
        jbtn_AddVacinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_AddVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AddVacinasActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_cadastrarPet.setUI(new RoundedCornerButtonUI());
        jPanel1.add(jbtn_AddVacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 122, 19));

        label_porte.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_porte.setForeground(new java.awt.Color(0, 0, 0));
        label_porte.setText("Porte:");
        jPanel1.add(label_porte, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 182, -1, -1));

        txtf_telefone.setBackground(new java.awt.Color(217, 217, 217));
        txtf_telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtf_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtf_telefone.setCaretColor(new java.awt.Color(0, 0, 0));
        txtf_telefone.setMinimumSize(new java.awt.Dimension(250, 50));
        txtf_telefone.setPreferredSize(new java.awt.Dimension(166, 50));
        jPanel1.add(txtf_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 201, 250, -1));

        label_cor.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_cor.setForeground(new java.awt.Color(0, 0, 0));
        label_cor.setText("Cor:");
        jPanel1.add(label_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        txtf_Cor.setBackground(new java.awt.Color(217, 217, 217));
        txtf_Cor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtf_Cor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtf_Cor.setCaretColor(new java.awt.Color(0, 0, 0));
        txtf_Cor.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel1.add(txtf_Cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 201, -1, -1));

        label_sexo.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_sexo.setForeground(new java.awt.Color(0, 0, 0));
        label_sexo.setText("Sexo:");
        jPanel1.add(label_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 182, -1, -1));

        jcmbBx_Sexo.setBackground(new java.awt.Color(217, 217, 217));
        jcmbBx_Sexo.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jcmbBx_Sexo.setForeground(new java.awt.Color(0, 0, 0));
        jcmbBx_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "Fêmea", "Macho" }));
        jcmbBx_Sexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcmbBx_Sexo.setMinimumSize(new java.awt.Dimension(232, 50));
        jcmbBx_Sexo.setPreferredSize(new java.awt.Dimension(232, 50));
        jPanel1.add(jcmbBx_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 201, -1, -1));

        label_comportamento_do_pet.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        label_comportamento_do_pet.setForeground(new java.awt.Color(0, 0, 0));
        label_comportamento_do_pet.setText("Comportamento do Pet:");
        jPanel1.add(label_comportamento_do_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 271, -1, -1));

        jtxtArea_Comportamento.setBackground(new java.awt.Color(217, 217, 217));
        jtxtArea_Comportamento.setBorder(null);
        jtxtArea_Comportamento.setForeground(new java.awt.Color(0, 0, 0));
        jtxtArea_Comportamento.setMinimumSize(new java.awt.Dimension(800, 80));
        jtxtArea_Comportamento.setPreferredSize(new java.awt.Dimension(800, 80));
        jtxtArea_Comportamento.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jtxtArea_Comportamento.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        jTextArea1.setBackground(new java.awt.Color(217, 217, 217));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(0);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextArea1.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setOpaque(false);
        jTextArea1.setPreferredSize(null);
        jtxtArea_Comportamento.setViewportView(jTextArea1);

        jPanel1.add(jtxtArea_Comportamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lbl_Saude.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        lbl_Saude.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Saude.setText("Saúde do Pet:");
        jPanel1.add(lbl_Saude, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 390, -1, -1));

        jtxtArea_Saude.setBackground(new java.awt.Color(217, 217, 217));
        jtxtArea_Saude.setBorder(null);
        jtxtArea_Saude.setForeground(new java.awt.Color(0, 0, 0));
        jtxtArea_Saude.setMinimumSize(new java.awt.Dimension(800, 80));
        jtxtArea_Saude.setPreferredSize(new java.awt.Dimension(800, 80));
        jtxtArea_Saude.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jtxtArea_Saude.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        jTextArea2.setBackground(new java.awt.Color(217, 217, 217));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(0);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextArea2.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setOpaque(false);
        jTextArea2.setPreferredSize(null);
        jtxtArea_Saude.setViewportView(jTextArea2);

        jPanel1.add(jtxtArea_Saude, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 409, -1, -1));

        jbtn_cadastrarPet.setBackground(new java.awt.Color(77, 120, 63));
        jbtn_cadastrarPet.setFont(new java.awt.Font("Merriweather", 0, 20)); // NOI18N
        jbtn_cadastrarPet.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_cadastrarPet.setText("CADASTRAR");
        jbtn_cadastrarPet.setBorder(null);
        jbtn_cadastrarPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_cadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cadastrarPetActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_cadastrarPet.setUI(new RoundedCornerButtonUI());
        jPanel1.add(jbtn_cadastrarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 240, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_nome_PetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_nome_PetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_nome_PetActionPerformed

    private void jbtn_cadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cadastrarPetActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
    }//GEN-LAST:event_jbtn_cadastrarPetActionPerformed

    private void chkBx_SimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_SimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBx_SimActionPerformed

    private void jbtn_AddVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AddVacinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_AddVacinasActionPerformed

    private void txtf_RacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_RacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_RacaActionPerformed
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro_pet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBx_Nao;
    private javax.swing.JCheckBox chkBx_Sim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton jbtn_AddVacinas;
    private javax.swing.JButton jbtn_cadastrarPet;
    private javax.swing.JComboBox<String> jcmbBx_Sexo;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JScrollPane jtxtArea_Comportamento;
    private javax.swing.JScrollPane jtxtArea_Saude;
    private javax.swing.JLabel label_comportamento_do_pet;
    private javax.swing.JLabel label_cor;
    private javax.swing.JLabel label_nome_do_pet;
    private javax.swing.JLabel label_porte;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel lbl_CadastrarPet;
    private javax.swing.JLabel lbl_Castrado;
    private javax.swing.JLabel lbl_Saude;
    private javax.swing.JLabel lbl_Vacinas;
    private javax.swing.JTextField txtf_Cor;
    private javax.swing.JTextField txtf_Raca;
    private javax.swing.JTextField txtf_nome_Pet;
    private javax.swing.JTextField txtf_telefone;
    // End of variables declaration//GEN-END:variables
}
