/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author kevin
 */
public class tela_redefinicao_senha extends javax.swing.JFrame {

    /**
     * Creates new form tela_redefinicao_senha
     */
    public tela_redefinicao_senha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_titulo_redefinicao_senha = new javax.swing.JLabel();
        jlbl_cpf = new javax.swing.JLabel();
        jfield_cpf = new javax.swing.JTextField();
        jlbl_nova_senha = new javax.swing.JLabel();
        jfield_nova_senha = new javax.swing.JTextField();
        jlbl_confirmacao_nova_senha = new javax.swing.JLabel();
        jfield_confirmacao_nova_senha = new javax.swing.JTextField();
        jbutton_redefinir_senha = new javax.swing.JButton();
        jlbl_background_cadastro_pet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(759, 583));

        jlbl_titulo_redefinicao_senha.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jlbl_titulo_redefinicao_senha.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_titulo_redefinicao_senha.setText("Redefinição de senha");

        jlbl_cpf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cpf.setText("CPF:");

        jfield_cpf.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cpf.setPreferredSize(new java.awt.Dimension(653, 60));
        jfield_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cpfActionPerformed(evt);
            }
        });

        jlbl_nova_senha.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_nova_senha.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nova_senha.setText("Nova senha:");

        jfield_nova_senha.setBackground(new java.awt.Color(255, 255, 255));
        jfield_nova_senha.setPreferredSize(new java.awt.Dimension(653, 60));

        jlbl_confirmacao_nova_senha.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_confirmacao_nova_senha.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_confirmacao_nova_senha.setText("Confirme a nova senha:");

        jfield_confirmacao_nova_senha.setBackground(new java.awt.Color(255, 255, 255));
        jfield_confirmacao_nova_senha.setPreferredSize(new java.awt.Dimension(653, 60));

        jbutton_redefinir_senha.setBackground(new java.awt.Color(71, 120, 63));
        jbutton_redefinir_senha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbutton_redefinir_senha.setForeground(new java.awt.Color(0, 0, 0));
        jbutton_redefinir_senha.setText("Redefinir senha");
        jbutton_redefinir_senha.setPreferredSize(new java.awt.Dimension(240, 50));
        jbutton_redefinir_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_redefinir_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jbutton_redefinir_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbl_titulo_redefinicao_senha)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfield_confirmacao_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_confirmacao_nova_senha)
                            .addComponent(jfield_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_nova_senha)
                            .addComponent(jlbl_cpf)
                            .addComponent(jfield_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbl_titulo_redefinicao_senha)
                .addGap(34, 34, 34)
                .addComponent(jlbl_cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jlbl_nova_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlbl_confirmacao_nova_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield_confirmacao_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jbutton_redefinir_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 145, -1, -1));

        jlbl_background_cadastro_pet.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Desktop\\PetAgenda\\src\\main\\java\\IMAGENS\\BG_padrao.png")); // NOI18N
        getContentPane().add(jlbl_background_cadastro_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfield_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cpfActionPerformed

    private void jbutton_redefinir_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_redefinir_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_redefinir_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_redefinicao_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_redefinicao_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_redefinicao_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_redefinicao_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_redefinicao_senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton_redefinir_senha;
    private javax.swing.JTextField jfield_confirmacao_nova_senha;
    private javax.swing.JTextField jfield_cpf;
    private javax.swing.JTextField jfield_nova_senha;
    private javax.swing.JLabel jlbl_background_cadastro_pet;
    private javax.swing.JLabel jlbl_confirmacao_nova_senha;
    private javax.swing.JLabel jlbl_cpf;
    private javax.swing.JLabel jlbl_nova_senha;
    private javax.swing.JLabel jlbl_titulo_redefinicao_senha;
    // End of variables declaration//GEN-END:variables
}
