/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import ui.custom.RoundedCornerBorder;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */
public class Tela_visualizacao_pet extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro_funcionario
     */
    public Tela_visualizacao_pet() {
        initComponents();
        configurarLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel_menu = new javax.swing.JPanel();
        btn_Home = new javax.swing.JToggleButton();
        btn_agenda = new javax.swing.JButton();
        btn_financeiro = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_funcionarios = new javax.swing.JButton();
        btn_pets = new javax.swing.JButton();
        btn_config = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbl_nomePet = new javax.swing.JLabel();
        jlbl_nomePetCadast = new javax.swing.JLabel();
        jlbl_raca = new javax.swing.JLabel();
        jlbl_racaCadastr = new javax.swing.JLabel();
        jlbl_porte = new javax.swing.JLabel();
        jlbl_porteCadast = new javax.swing.JLabel();
        jlbl_cor = new javax.swing.JLabel();
        lbl_corCadast = new javax.swing.JLabel();
        jlbl_sexo = new javax.swing.JLabel();
        jlbl_sexoCadast = new javax.swing.JLabel();
        jlbl_descricaoComport = new javax.swing.JLabel();
        jlbl_descricaoCadast = new javax.swing.JLabel();
        jlbl_saude = new javax.swing.JLabel();
        jlbl_saudeCadast = new javax.swing.JLabel();
        jbtn_visualizarHistorico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbl_nomePet1 = new javax.swing.JLabel();
        jlbl_nomePetCadast1 = new javax.swing.JLabel();
        jlbl_raca1 = new javax.swing.JLabel();
        jlbl_racaCadastr1 = new javax.swing.JLabel();
        jlbl_porte1 = new javax.swing.JLabel();
        jlbl_porteCadast1 = new javax.swing.JLabel();
        jlbl_cor1 = new javax.swing.JLabel();
        lbl_corCadast1 = new javax.swing.JLabel();
        jlbl_sexo1 = new javax.swing.JLabel();
        lbl_sexoCadast1 = new javax.swing.JLabel();
        jlbl_descricaoComport1 = new javax.swing.JLabel();
        jlbl_descricaoCadast1 = new javax.swing.JLabel();
        jlbl_saude1 = new javax.swing.JLabel();
        jlbl_saudeCadast1 = new javax.swing.JLabel();
        jbtn_visualizarHistorico1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlbl_nomePet2 = new javax.swing.JLabel();
        jlbl_nomePetCadast2 = new javax.swing.JLabel();
        jlbl_raca2 = new javax.swing.JLabel();
        jlbl_racaCadastr2 = new javax.swing.JLabel();
        jlbl_porte2 = new javax.swing.JLabel();
        jlbl_porteCadast2 = new javax.swing.JLabel();
        jlbl_cor2 = new javax.swing.JLabel();
        lbl_corCadast2 = new javax.swing.JLabel();
        jlbl_sexo2 = new javax.swing.JLabel();
        lbl_sexoCadast2 = new javax.swing.JLabel();
        jlbl_descricaoComport2 = new javax.swing.JLabel();
        jlbl_descricaoCadast2 = new javax.swing.JLabel();
        jlbl_saude2 = new javax.swing.JLabel();
        jlbl_saudeCadast2 = new javax.swing.JLabel();
        jbtn_visualizarHistorico2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlbl_nomePet3 = new javax.swing.JLabel();
        jlbl_nomePetCadast3 = new javax.swing.JLabel();
        jlbl_raca3 = new javax.swing.JLabel();
        jlbl_racaCadastr3 = new javax.swing.JLabel();
        jlbl_porte3 = new javax.swing.JLabel();
        jlbl_porteCadast3 = new javax.swing.JLabel();
        jlbl_cor3 = new javax.swing.JLabel();
        lbl_corCadast3 = new javax.swing.JLabel();
        jlbl_sexo3 = new javax.swing.JLabel();
        lbl_sexoCadast3 = new javax.swing.JLabel();
        jlbl_descricaoComport3 = new javax.swing.JLabel();
        jlbl_descricaoCadast3 = new javax.swing.JLabel();
        jlbl_saude3 = new javax.swing.JLabel();
        jlbl_saudeCadast3 = new javax.swing.JLabel();
        jbtn_visualizarHistorico3 = new javax.swing.JButton();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(905, 560));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(905, 560));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.setLayout(new java.awt.GridLayout(0, 2)); // 0 significa que o número de linhas será ajustado automaticamente

        // Criação de sub-painéis
        for (int i = 0; i < 10; i++) { // Altere 10 para o número total de subpainéis que deseja criar
            javax.swing.JPanel subPanel = new javax.swing.JPanel();
            subPanel.setBackground(new java.awt.Color(255, 255, 255));
            subPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
            subPanel.add(new javax.swing.JLabel("Sub-painel " + (i + 1))); // Exemplo de adição de um componente

            jPanel6.add(subPanel); // Adicionando o sub-painel ao jPanel6
        }

        jScrollBar1.setOrientation(JScrollBar.VERTICAL);
        jPanel6.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 0, -1, 560));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 51, -1, -1));

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(124, 115, 101));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_PetAgendaMenor.png"))); // NOI18N
        btn_Home.setBorder(null);
        btn_Home.setBorderPainted(false);
        btn_Home.setContentAreaFilled(false);
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.setFocusPainted(false);
        btn_Home.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_PetAgendaPressed.png"))); // NOI18N
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_HomeMouseReleased(evt);
            }
        });
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });
        jPanel_menu.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 193, -1));

        btn_agenda.setBackground(new java.awt.Color(124, 115, 101));
        btn_agenda.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_agenda.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_agenda.png"))); // NOI18N
        btn_agenda.setText("Agenda");
        btn_agenda.setBorder(null);
        btn_agenda.setBorderPainted(false);
        btn_agenda.setContentAreaFilled(false);
        btn_agenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agenda.setFocusPainted(false);
        btn_agenda.setHideActionText(true);
        btn_agenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_agenda.setIconTextGap(8);
        btn_agenda.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_agenda.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_agenda.setPreferredSize(new java.awt.Dimension(205, 60));
        btn_agenda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_agendaMouseMoved(evt);
            }
        });
        btn_agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agendaMousePressed(evt);
            }
        });
        btn_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendaActionPerformed(evt);
            }
        });
        jPanel_menu.add(btn_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 248, -1, -1));

        btn_financeiro.setBackground(new java.awt.Color(124, 115, 101));
        btn_financeiro.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_financeiro.setForeground(new java.awt.Color(255, 255, 255));
        btn_financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_financeiro.png"))); // NOI18N
        btn_financeiro.setText("Financeiro");
        btn_financeiro.setBorder(null);
        btn_financeiro.setContentAreaFilled(false);
        btn_financeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_financeiro.setHideActionText(true);
        btn_financeiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_financeiro.setIconTextGap(8);
        btn_financeiro.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_financeiro.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_financeiro.setPreferredSize(new java.awt.Dimension(205, 60));
        btn_financeiro.setSelected(true);
        jPanel_menu.add(btn_financeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 308, -1, -1));

        btn_clientes.setBackground(new java.awt.Color(124, 115, 101));
        btn_clientes.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_clientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_clientes.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.setBorder(null);
        btn_clientes.setContentAreaFilled(false);
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clientes.setHideActionText(true);
        btn_clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_clientes.setIconTextGap(8);
        btn_clientes.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_clientes.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_clientes.setPreferredSize(new java.awt.Dimension(205, 60));
        jPanel_menu.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, -1, -1));

        btn_funcionarios.setBackground(new java.awt.Color(124, 115, 101));
        btn_funcionarios.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_funcionario.png"))); // NOI18N
        btn_funcionarios.setText("Funcionários");
        btn_funcionarios.setBorder(null);
        btn_funcionarios.setContentAreaFilled(false);
        btn_funcionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_funcionarios.setHideActionText(true);
        btn_funcionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_funcionarios.setIconTextGap(8);
        btn_funcionarios.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_funcionarios.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_funcionarios.setPreferredSize(new java.awt.Dimension(205, 60));
        jPanel_menu.add(btn_funcionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 428, -1, -1));

        btn_pets.setBackground(new java.awt.Color(124, 115, 101));
        btn_pets.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_pets.setForeground(new java.awt.Color(255, 255, 255));
        btn_pets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_pets.png"))); // NOI18N
        btn_pets.setText("Pets");
        btn_pets.setBorder(null);
        btn_pets.setContentAreaFilled(false);
        btn_pets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pets.setHideActionText(true);
        btn_pets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pets.setIconTextGap(8);
        btn_pets.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_pets.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_pets.setPreferredSize(new java.awt.Dimension(205, 60));
        jPanel_menu.add(btn_pets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 488, -1, -1));

        btn_config.setBackground(new java.awt.Color(124, 115, 101));
        btn_config.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_config.setForeground(new java.awt.Color(255, 255, 255));
        btn_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_configuracoes.png"))); // NOI18N
        btn_config.setText("Configurações");
        btn_config.setBorder(null);
        btn_config.setContentAreaFilled(false);
        btn_config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_config.setHideActionText(true);
        btn_config.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_config.setIconTextGap(8);
        btn_config.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_config.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_config.setPreferredSize(new java.awt.Dimension(205, 60));
        jPanel_menu.add(btn_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 548, -1, -1));

        btn_sair.setBackground(new java.awt.Color(124, 115, 101));
        btn_sair.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_sair.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setBorder(null);
        btn_sair.setContentAreaFilled(false);
        btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sair.setHideActionText(true);
        btn_sair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sair.setIconTextGap(8);
        btn_sair.setMaximumSize(new java.awt.Dimension(205, 50));
        btn_sair.setMinimumSize(new java.awt.Dimension(205, 50));
        btn_sair.setPreferredSize(new java.awt.Dimension(205, 60));
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        jPanel_menu.add(btn_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 608, -1, -1));

        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setMinimumSize(new java.awt.Dimension(670, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nomePet.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_nomePet.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_nomePet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nomePet.setText("Nome do pet:");
        jlbl_nomePet.setPreferredSize(new java.awt.Dimension(165, 20));
        jPanel1.add(jlbl_nomePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jlbl_nomePetCadast.setText("<insert>");
        jPanel1.add(jlbl_nomePetCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlbl_raca.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_raca.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_raca.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca.setText("Raça:");
        jlbl_raca.setMaximumSize(new java.awt.Dimension(71, 20));
        jlbl_raca.setMinimumSize(new java.awt.Dimension(71, 20));
        jlbl_raca.setPreferredSize(new java.awt.Dimension(71, 20));
        jPanel1.add(jlbl_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jlbl_racaCadastr.setText("<insert>");
        jPanel1.add(jlbl_racaCadastr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jlbl_porte.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_porte.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_porte.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte.setText("Porte:");
        jPanel1.add(jlbl_porte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jlbl_porteCadast.setText("<insert>");
        jPanel1.add(jlbl_porteCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jlbl_cor.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_cor.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_cor.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor.setText("Cor:");
        jPanel1.add(jlbl_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_corCadast.setText("<insert>");
        jPanel1.add(lbl_corCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jlbl_sexo.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_sexo.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_sexo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo.setText("Sexo:");
        jPanel1.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jlbl_sexoCadast.setText("<insert>");
        jPanel1.add(jlbl_sexoCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jlbl_descricaoComport.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_descricaoComport.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_descricaoComport.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricaoComport.setText("Descrição do comportamento:");
        jPanel1.add(jlbl_descricaoComport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlbl_descricaoCadast.setText("<insert>");
        jPanel1.add(jlbl_descricaoCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jlbl_saude.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_saude.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_saude.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_saude.setText("Saúde do pet:");
        jPanel1.add(jlbl_saude, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlbl_saudeCadast.setText("<insert>");
        jPanel1.add(jlbl_saudeCadast, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jbtn_visualizarHistorico.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_visualizarHistorico.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jbtn_visualizarHistorico.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_visualizarHistorico.setText("Visualizar histórico");
        jbtn_visualizarHistorico.setBorder(null);
        jbtn_visualizarHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_visualizarHistorico.setPreferredSize(new java.awt.Dimension(170, 30));
        jbtn_visualizarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_visualizarHistoricoActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_visualizarHistorico.setUI(new RoundedCornerButtonUI());
        jPanel1.add(jbtn_visualizarHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 51, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(670, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nomePet1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_nomePet1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_nomePet1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nomePet1.setText("Nome do pet:");
        jlbl_nomePet1.setPreferredSize(new java.awt.Dimension(165, 20));
        jPanel2.add(jlbl_nomePet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        jlbl_nomePetCadast1.setText("<insert>");
        jPanel2.add(jlbl_nomePetCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlbl_raca1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_raca1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_raca1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca1.setText("Raça:");
        jlbl_raca1.setMaximumSize(new java.awt.Dimension(71, 20));
        jlbl_raca1.setMinimumSize(new java.awt.Dimension(71, 20));
        jlbl_raca1.setPreferredSize(new java.awt.Dimension(71, 20));
        jPanel2.add(jlbl_raca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jlbl_racaCadastr1.setText("<insert>");
        jPanel2.add(jlbl_racaCadastr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jlbl_porte1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_porte1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_porte1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte1.setText("Porte:");
        jPanel2.add(jlbl_porte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jlbl_porteCadast1.setText("<insert>");
        jPanel2.add(jlbl_porteCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jlbl_cor1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_cor1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_cor1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor1.setText("Cor:");
        jPanel2.add(jlbl_cor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_corCadast1.setText("<insert>");
        jPanel2.add(lbl_corCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jlbl_sexo1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_sexo1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_sexo1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo1.setText("Sexo:");
        jPanel2.add(jlbl_sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_sexoCadast1.setText("<insert>");
        jPanel2.add(lbl_sexoCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jlbl_descricaoComport1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_descricaoComport1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_descricaoComport1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricaoComport1.setText("Descrição do comportamento:");
        jPanel2.add(jlbl_descricaoComport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlbl_descricaoCadast1.setText("<insert>");
        jPanel2.add(jlbl_descricaoCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jlbl_saude1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_saude1.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_saude1.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_saude1.setText("Saúde do pet:");
        jPanel2.add(jlbl_saude1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlbl_saudeCadast1.setText("<insert>");
        jPanel2.add(jlbl_saudeCadast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jbtn_visualizarHistorico1.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_visualizarHistorico1.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jbtn_visualizarHistorico1.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_visualizarHistorico1.setText("Visualizar histórico");
        jbtn_visualizarHistorico1.setBorder(null);
        jbtn_visualizarHistorico1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_visualizarHistorico1.setPreferredSize(new java.awt.Dimension(170, 30));
        jbtn_visualizarHistorico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_visualizarHistorico1ActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_visualizarHistorico1.setUI(new RoundedCornerButtonUI());
        jPanel2.add(jbtn_visualizarHistorico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setMinimumSize(new java.awt.Dimension(670, 640));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nomePet2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_nomePet2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_nomePet2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nomePet2.setText("Nome do pet:");
        jlbl_nomePet2.setPreferredSize(new java.awt.Dimension(165, 20));
        jPanel3.add(jlbl_nomePet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        jlbl_nomePetCadast2.setText("<insert>");
        jPanel3.add(jlbl_nomePetCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlbl_raca2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_raca2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_raca2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca2.setText("Raça:");
        jlbl_raca2.setMaximumSize(new java.awt.Dimension(71, 20));
        jlbl_raca2.setMinimumSize(new java.awt.Dimension(71, 20));
        jlbl_raca2.setPreferredSize(new java.awt.Dimension(71, 20));
        jPanel3.add(jlbl_raca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jlbl_racaCadastr2.setText("<insert>");
        jPanel3.add(jlbl_racaCadastr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jlbl_porte2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_porte2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_porte2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte2.setText("Porte:");
        jPanel3.add(jlbl_porte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jlbl_porteCadast2.setText("<insert>");
        jPanel3.add(jlbl_porteCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jlbl_cor2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_cor2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_cor2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor2.setText("Cor:");
        jPanel3.add(jlbl_cor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_corCadast2.setText("<insert>");
        jPanel3.add(lbl_corCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jlbl_sexo2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_sexo2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_sexo2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo2.setText("Sexo:");
        jPanel3.add(jlbl_sexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_sexoCadast2.setText("<insert>");
        jPanel3.add(lbl_sexoCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jlbl_descricaoComport2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_descricaoComport2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_descricaoComport2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricaoComport2.setText("Descrição do comportamento:");
        jPanel3.add(jlbl_descricaoComport2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlbl_descricaoCadast2.setText("<insert>");
        jPanel3.add(jlbl_descricaoCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jlbl_saude2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_saude2.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_saude2.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_saude2.setText("Saúde do pet:");
        jPanel3.add(jlbl_saude2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlbl_saudeCadast2.setText("<insert>");
        jPanel3.add(jlbl_saudeCadast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jbtn_visualizarHistorico2.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_visualizarHistorico2.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jbtn_visualizarHistorico2.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_visualizarHistorico2.setText("Visualizar histórico");
        jbtn_visualizarHistorico2.setBorder(null);
        jbtn_visualizarHistorico2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_visualizarHistorico2.setPreferredSize(new java.awt.Dimension(170, 30));
        jbtn_visualizarHistorico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_visualizarHistorico2ActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_visualizarHistorico2.setUI(new RoundedCornerButtonUI());
        jPanel3.add(jbtn_visualizarHistorico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 361, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setMinimumSize(new java.awt.Dimension(670, 640));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nomePet3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_nomePet3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_nomePet3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nomePet3.setText("Nome do pet:");
        jlbl_nomePet3.setPreferredSize(new java.awt.Dimension(165, 20));
        jPanel4.add(jlbl_nomePet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        jlbl_nomePetCadast3.setText("<insert>");
        jPanel4.add(jlbl_nomePetCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlbl_raca3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_raca3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_raca3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca3.setText("Raça:");
        jlbl_raca3.setMaximumSize(new java.awt.Dimension(71, 20));
        jlbl_raca3.setMinimumSize(new java.awt.Dimension(71, 20));
        jlbl_raca3.setPreferredSize(new java.awt.Dimension(71, 20));
        jPanel4.add(jlbl_raca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jlbl_racaCadastr3.setText("<insert>");
        jPanel4.add(jlbl_racaCadastr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jlbl_porte3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_porte3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_porte3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte3.setText("Porte:");
        jPanel4.add(jlbl_porte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jlbl_porteCadast3.setText("<insert>");
        jPanel4.add(jlbl_porteCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jlbl_cor3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_cor3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_cor3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor3.setText("Cor:");
        jPanel4.add(jlbl_cor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_corCadast3.setText("<insert>");
        jPanel4.add(lbl_corCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jlbl_sexo3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_sexo3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_sexo3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo3.setText("Sexo:");
        jPanel4.add(jlbl_sexo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_sexoCadast3.setText("<insert>");
        jPanel4.add(lbl_sexoCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jlbl_descricaoComport3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_descricaoComport3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_descricaoComport3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricaoComport3.setText("Descrição do comportamento:");
        jPanel4.add(jlbl_descricaoComport3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlbl_descricaoCadast3.setText("<insert>");
        jPanel4.add(jlbl_descricaoCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jlbl_saude3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_saude3.setFont(new java.awt.Font("Merriweather", 1, 15)); // NOI18N
        jlbl_saude3.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_saude3.setText("Saúde do pet:");
        jPanel4.add(jlbl_saude3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlbl_saudeCadast3.setText("<insert>");
        jPanel4.add(jlbl_saudeCadast3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jbtn_visualizarHistorico3.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_visualizarHistorico3.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jbtn_visualizarHistorico3.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_visualizarHistorico3.setText("Visualizar histórico");
        jbtn_visualizarHistorico3.setBorder(null);
        jbtn_visualizarHistorico3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_visualizarHistorico3.setPreferredSize(new java.awt.Dimension(170, 30));
        jbtn_visualizarHistorico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_visualizarHistorico3ActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_visualizarHistorico3.setUI(new RoundedCornerButtonUI());
        jPanel4.add(jbtn_visualizarHistorico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 361, -1, -1));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        jlbl_background.setText(" ");
        jlbl_background.setMaximumSize(new java.awt.Dimension(1366, 768));
        jlbl_background.setMinimumSize(new java.awt.Dimension(1366, 768));
        jlbl_background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HomeMousePressed

    private void btn_HomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HomeMouseReleased

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        Tela_Inicial telaPrincipal = new Tela_Inicial();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_agendaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agendaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agendaMouseMoved

    private void btn_agendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agendaMousePressed
        // TODO add your handling code here:
        btn_agenda.setBackground(new java.awt.Color(99, 90, 77));
    }//GEN-LAST:event_btn_agendaMousePressed

    private void jbtn_visualizarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_visualizarHistoricoActionPerformed
        // TODO add your handling code here:
        //Inserir lógica
    }//GEN-LAST:event_jbtn_visualizarHistoricoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        //Adicionar conexão com o banco de dados
        TELA_LOGIN telaLogin = new TELA_LOGIN();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendaActionPerformed
        // TODO add your handling code here:
        Tela_de_visualizacao_do_mes telaVisualizaMes = new Tela_de_visualizacao_do_mes();
        telaVisualizaMes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agendaActionPerformed

    private void jbtn_visualizarHistorico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_visualizarHistorico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_visualizarHistorico1ActionPerformed

    private void jbtn_visualizarHistorico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_visualizarHistorico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_visualizarHistorico2ActionPerformed

    private void jbtn_visualizarHistorico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_visualizarHistorico3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_visualizarHistorico3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_visualizacao_pet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Home;
    private javax.swing.JButton btn_agenda;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_config;
    private javax.swing.JButton btn_financeiro;
    private javax.swing.JButton btn_funcionarios;
    private javax.swing.JButton btn_pets;
    private javax.swing.JButton btn_sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton jbtn_visualizarHistorico;
    private javax.swing.JButton jbtn_visualizarHistorico1;
    private javax.swing.JButton jbtn_visualizarHistorico2;
    private javax.swing.JButton jbtn_visualizarHistorico3;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JLabel jlbl_cor;
    private javax.swing.JLabel jlbl_cor1;
    private javax.swing.JLabel jlbl_cor2;
    private javax.swing.JLabel jlbl_cor3;
    private javax.swing.JLabel jlbl_descricaoCadast;
    private javax.swing.JLabel jlbl_descricaoCadast1;
    private javax.swing.JLabel jlbl_descricaoCadast2;
    private javax.swing.JLabel jlbl_descricaoCadast3;
    private javax.swing.JLabel jlbl_descricaoComport;
    private javax.swing.JLabel jlbl_descricaoComport1;
    private javax.swing.JLabel jlbl_descricaoComport2;
    private javax.swing.JLabel jlbl_descricaoComport3;
    private javax.swing.JLabel jlbl_nomePet;
    private javax.swing.JLabel jlbl_nomePet1;
    private javax.swing.JLabel jlbl_nomePet2;
    private javax.swing.JLabel jlbl_nomePet3;
    private javax.swing.JLabel jlbl_nomePetCadast;
    private javax.swing.JLabel jlbl_nomePetCadast1;
    private javax.swing.JLabel jlbl_nomePetCadast2;
    private javax.swing.JLabel jlbl_nomePetCadast3;
    private javax.swing.JLabel jlbl_porte;
    private javax.swing.JLabel jlbl_porte1;
    private javax.swing.JLabel jlbl_porte2;
    private javax.swing.JLabel jlbl_porte3;
    private javax.swing.JLabel jlbl_porteCadast;
    private javax.swing.JLabel jlbl_porteCadast1;
    private javax.swing.JLabel jlbl_porteCadast2;
    private javax.swing.JLabel jlbl_porteCadast3;
    private javax.swing.JLabel jlbl_raca;
    private javax.swing.JLabel jlbl_raca1;
    private javax.swing.JLabel jlbl_raca2;
    private javax.swing.JLabel jlbl_raca3;
    private javax.swing.JLabel jlbl_racaCadastr;
    private javax.swing.JLabel jlbl_racaCadastr1;
    private javax.swing.JLabel jlbl_racaCadastr2;
    private javax.swing.JLabel jlbl_racaCadastr3;
    private javax.swing.JLabel jlbl_saude;
    private javax.swing.JLabel jlbl_saude1;
    private javax.swing.JLabel jlbl_saude2;
    private javax.swing.JLabel jlbl_saude3;
    private javax.swing.JLabel jlbl_saudeCadast;
    private javax.swing.JLabel jlbl_saudeCadast1;
    private javax.swing.JLabel jlbl_saudeCadast2;
    private javax.swing.JLabel jlbl_saudeCadast3;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jlbl_sexo1;
    private javax.swing.JLabel jlbl_sexo2;
    private javax.swing.JLabel jlbl_sexo3;
    private javax.swing.JLabel jlbl_sexoCadast;
    private javax.swing.JLabel lbl_corCadast;
    private javax.swing.JLabel lbl_corCadast1;
    private javax.swing.JLabel lbl_corCadast2;
    private javax.swing.JLabel lbl_corCadast3;
    private javax.swing.JLabel lbl_sexoCadast1;
    private javax.swing.JLabel lbl_sexoCadast2;
    private javax.swing.JLabel lbl_sexoCadast3;
    // End of variables declaration//GEN-END:variables

    private void configurarLayout() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
