/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author The Great Garibaldo
 */
public class TELA_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form TELA_LOGIN
     */
    public TELA_LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ENTRAR = new javax.swing.JButton();
        jButton_Cadastrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel_LOGIN = new javax.swing.JLabel();
        jLabel_SENHA = new javax.swing.JLabel();
        jLabel_ImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_ENTRAR.setBackground(new java.awt.Color(239, 225, 201));
        jButton_ENTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao_osso_entrar.png"))); // NOI18N
        jButton_ENTRAR.setBorder(null);
        jButton_ENTRAR.setBorderPainted(false);
        jButton_ENTRAR.setContentAreaFilled(false);
        jButton_ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 190, 90));

        jButton_Cadastrar.setBackground(new java.awt.Color(239, 225, 201));
        jButton_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao_osso_cadastrar.png"))); // NOI18N
        jButton_Cadastrar.setBorder(null);
        jButton_Cadastrar.setBorderPainted(false);
        jButton_Cadastrar.setContentAreaFilled(false);
        jButton_Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 190, 90));

        jTextField1.setText("TheMasterOfTheMasterAdmin");
        jTextField1.setMinimumSize(new java.awt.Dimension(466, 41));
        jTextField1.setPreferredSize(new java.awt.Dimension(466, 41));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 299, 466, 41));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 445, 466, 41));

        jLabel_LOGIN.setFont(new java.awt.Font("Merriweather", 0, 32)); // NOI18N
        jLabel_LOGIN.setText("Login");
        jLabel_LOGIN.setMaximumSize(new java.awt.Dimension(123, 49));
        jLabel_LOGIN.setMinimumSize(new java.awt.Dimension(123, 49));
        jLabel_LOGIN.setPreferredSize(new java.awt.Dimension(123, 49));
        getContentPane().add(jLabel_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 250, 110, 50));

        jLabel_SENHA.setFont(new java.awt.Font("Merriweather", 0, 32)); // NOI18N
        jLabel_SENHA.setText("Senha");
        getContentPane().add(jLabel_SENHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 396, 130, 40));

        jLabel_ImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_LOGIN.png"))); // NOI18N
        jLabel_ImgFundo.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel_ImgFundo.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel_ImgFundo.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel_ImgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ENTRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ENTRARActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_ENTRAR;
    private javax.swing.JLabel jLabel_ImgFundo;
    private javax.swing.JLabel jLabel_LOGIN;
    private javax.swing.JLabel jLabel_SENHA;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
