-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 22:56:28 2024
-- Model: Modelo físico PetAgenda    Version: 0.9
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pet_agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pet_agenda` ;

-- -----------------------------------------------------
-- Schema pet_agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pet_agenda` DEFAULT CHARACTER SET utf8 ;
USE `pet_agenda` ;

-- -----------------------------------------------------
-- Table `pet_agenda`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`endereco` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`endereco` (
  `id` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(16) NOT NULL,
  `bairro` VARCHAR(32) NOT NULL,
  `cidade` VARCHAR(32) NOT NULL,
  `cep` CHAR(8) NOT NULL COMMENT 'CEP no formato numérico (12345678).',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`tipo_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`tipo_servico` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`tipo_servico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`servico_disponivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`servico_disponivel` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`servico_disponivel` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_tipo_servico` INT NOT NULL,
  `duracao` INT NOT NULL COMMENT 'Duração em minutos necessária para realização do serviço',
  `preco` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_tipo_servico`)
    REFERENCES `pet_agenda`.`tipo_servico` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`cliente` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`cliente` (
  `id` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `nome` VARCHAR(64) NOT NULL,
  `cpf` CHAR(11) NULL COMMENT 'CPF do cliente no formato numérico, exemplo: 12345678912',
  `telefone` VARCHAR(12) NOT NULL COMMENT 'Número de telefone do cliente no formato numérico, exemplo: 27123456789',
  `id_servico_solicita` INT NOT NULL,
  `buscar_com` VARCHAR(64) NULL,
  `devolver_para` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_endereco`)
    REFERENCES `pet_agenda`.`endereco` (`id`),
    FOREIGN KEY (`id_servico_solicita`)
    REFERENCES `pet_agenda`.`servico_disponivel` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`permissao` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`permissao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`local_atuacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`local_atuacao` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`local_atuacao` (
  `id` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(64) NOT NULL,
  `id_endereco` INT NULL,
  `cpf` CHAR(11) NULL,
  `telefone` VARCHAR(12) NOT NULL COMMENT 'Número de telefone do usuário no formato numérico, exemplo: 27123456789',
  `senha` VARCHAR(32) NULL,
  `id_servico_presta` INT NOT NULL,
  `id_permissao` INT NULL COMMENT 'Grupo de permissão do usuário dentro do sistema.',
  `id_local_atuacao` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_endereco`)
    REFERENCES `pet_agenda`.`endereco` (`id`),
    FOREIGN KEY (`id_servico_presta`)
    REFERENCES `pet_agenda`.`servico_disponivel` (`id`),
    FOREIGN KEY (`id_permissao`)
    REFERENCES `pet_agenda`.`permissao` (`id`),
    FOREIGN KEY (`id_local_atuacao`)
    REFERENCES `pet_agenda`.`local_atuacao` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`pet` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`pet` (
  `id` INT NOT NULL,
  `id_cliente_dono` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(16) NULL,
  `raca` VARCHAR(45) NOT NULL,
  `sexo` ENUM("M", "F") NOT NULL,
  `porte` VARCHAR(20) NULL,
  `comportamento` VARCHAR(80) NULL,
  `e_castrado` BIT(1) NOT NULL,
  `caminho_cartao_vacinacao` VARCHAR(255) NULL,
  `estado_saude` VARCHAR(80) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_cliente_dono`)
    REFERENCES `pet_agenda`.`cliente` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`pacote_agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`pacote_agendamento` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`pacote_agendamento` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`agendamento` (
  `id` INT NOT NULL,
  `id_servico` INT NOT NULL,
  `id_tipo_servico` INT NOT NULL,
  `dt_hr_marcada` DATETIME NOT NULL,
  `id_pet` INT NOT NULL,
  `endereco_pet` VARCHAR(255) NOT NULL COMMENT 'Endereço de onde o Pet deverá ser buscado. Conterá o endereço de forma concatenada e separado por vírgulas.',
  `id_funcionario_agend` INT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  `id_pacote_agendamento` INT NULL,
  `pet_buscar_com` VARCHAR(64) NULL,
  `pet_devolver_para` VARCHAR(64) NULL,
  `qnt_passeios` INT NOT NULL DEFAULT 0,
  `local_cuidado` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_servico`)
    REFERENCES `pet_agenda`.`servico_disponivel` (`id`),
    FOREIGN KEY (`id_pet`)
    REFERENCES `pet_agenda`.`pet` (`id`),
    FOREIGN KEY (`id_funcionario_agend`)
    REFERENCES `pet_agenda`.`usuario` (`id`),
    FOREIGN KEY (`id_pacote_agendamento`)
    REFERENCES `pet_agenda`.`pacote_agendamento` (`id`),
    FOREIGN KEY (`id_tipo_servico`)
    REFERENCES `pet_agenda`.`tipo_servico` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`remedio_agend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`remedio_agend` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`remedio_agend` (
  `id_agendamento` INT NOT NULL,
  `remedio` VARCHAR(64) NOT NULL,
  `hr_administrar` TIME NOT NULL,
  `instrucoes` VARCHAR(120) NULL,
  PRIMARY KEY (`id_agendamento`, `remedio`),
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `pet_agenda`.`agendamento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`hr_alim_agend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`hr_alim_agend` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`hr_alim_agend` (
  `id_agendamento` INT NOT NULL,
  `hr_alimentacao` TIME NOT NULL,
  PRIMARY KEY (`id_agendamento`, `hr_alimentacao`),
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `pet_agenda`.`agendamento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_agenda`.`incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`incidente` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`incidente` (
  `id` INT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `e_emergencia` BIT(1) NOT NULL DEFAULT b'0',
  `id_pet` INT NOT NULL,
  `id_servico_contratado` INT NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_pet`)
    REFERENCES `pet_agenda`.`pet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id_servico_contratado`)
    REFERENCES `pet_agenda`.`servico_disponivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`historico_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`historico_servico` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`historico_servico` (
  `id_historico_servico` INT NOT NULL AUTO_INCREMENT,
  `id_agendamento` INT NOT NULL,
  `descricao` TEXT NULL,
  `dt_hr_finalizado` DATETIME NOT NULL,
  `duracao` INT NOT NULL COMMENT 'Tempo, em minutos, que levou para o serviço ser concluído.',
  `observacao` VARCHAR(255) NULL,
  `comportamento_pet` VARCHAR(120) NULL,
  `id_incidente` INT NULL,
  PRIMARY KEY (`id_historico_servico`, `id_agendamento`),
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `pet_agenda`.`agendamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id_incidente`)
    REFERENCES `pet_agenda`.`incidente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_agenda`.`anexo_historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet_agenda`.`anexo_historico` ;

CREATE TABLE IF NOT EXISTS `pet_agenda`.`anexo_historico` (
  `id_historico_servico` INT NOT NULL,
  `nome` VARCHAR(64) NOT NULL,
  `caminho_anexo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_historico_servico`, `caminho_anexo`),
    FOREIGN KEY (`id_historico_servico`)
    REFERENCES `pet_agenda`.`historico_servico` (`id_historico_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
